filebeat:
  prospectors:
    -
      paths:
        - /var/log/apache2/ckan.log
      multiline:
        pattern: '^\[.*?\] (Error|[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]+)'
        negate: true
        match: after
      input_type: log
      document_type: catalog-apache
      fields:
        environment: "{{ deployment_environment_id }}"

  #spool_size: 1024
  #idle_timeout: 5s

  registry_file: /var/lib/filebeat/registry
  #config_dir:

output:
  logstash:
    hosts: ["{{ elk.logstash.hostname }}:{{ elk.logstash.port }}"]
    worker: 1
    loadbalance: false
    #tls:
    #certificate_authorities: ["/etc/ssl/foobar_filebeat/ca_cert.crt"]
    #certificate: "/etc/ssl/foobar_filebeat/foobar-filebeat-{{ deployment_environment_id }}.crt"
    #certificate_key: "/etc/ssl/foobar_filebeat/foobar-filebeat-{{ deployment_environment_id }}.key"
    #insecure: false
  #console:
  #  pretty: true

shipper:

logging:
  to_syslog: false
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    # 10485760 = 10MB
    rotateeverybytes: 10485760
    keepfiles: 7
  level: warning
